name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH into EC2 and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy project to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no . ec2-user@54.91.83.80:/home/ec2-user/app

      - name: SSH and Restart Uvicorn
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.91.83.80 << 'EOF'
            cd /home/ec2-user/app
            source venv/bin/activate
            pip install -r requirements.txt
            pkill -f "uvicorn"
            nohup uvicorn app:app --host 0.0.0.0 --port 8080 &
          EOF
